spring:
  datasource:
    url: jdbc:postgresql://<localhost>:5432/<database>
    username: <user>
    password: <pswd>
  jpa:
    generate-ddl: true
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: <servers>
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

auto.create.topics.enable: true

server.port: 9090

order.topic.name: <topic>